#!/usr/bin/env node

var path = require("path");
var spawn = require("child_process").spawn;
require('./utils/config')

var pkgInfo = require(path.resolve(__dirname, '..', 'package.json'));

var target = path.resolve(__dirname, '..', 'dist/');

var theArgs = process.argv.slice(2);
if (theArgs.length < 1) {
  theArgs = ['-r', '.'];
}

// Linux
var cmd = path.join(target, pkgInfo.productName, 'electron');

if (process.platform === 'darwin') {
  cmd = path.join(target, pkgInfo.productName + '.app', 'Contents', 'MacOS', 'Electron');
}

if (process.platform === 'win32') {
  cmd = path.join(target, pkgInfo.productName, 'electron.exe');
}

var toRun = cmd + " " + theArgs.join(" ");
console.log("Running: " + toRun);
var child = spawn(cmd, theArgs);
child.stdout.on('data', function(data) {
  console.log(data.toString());
});
child.stderr.on('data', function(data) {
  console.error(data.toString());
});
child.on('close', function(exitValue) {
  process.exit(exitValue);
});
